"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";

const uses: Record<string, ComponentType> = {
  "accordion": dynamic(() => import("./accordion/use").then((m) => m.Use)),
  "alert": dynamic(() => import("./alert/use").then((m) => m.Use)),
  "alert-dialog": dynamic(() => import("./alert-dialog/use").then((m) => m.Use)),
  "aspect-ratio": dynamic(() => import("./aspect-ratio/use").then((m) => m.Use)),
  "assistant": dynamic(() => import("./assistant/use").then((m) => m.Use)),
  "avatar": dynamic(() => import("./avatar/use").then((m) => m.Use)),
  "badge": dynamic(() => import("./badge/use").then((m) => m.Use)),
  "breadcrumbs": dynamic(() => import("./breadcrumbs/use").then((m) => m.Use)),
  "button": dynamic(() => import("./button/use").then((m) => m.Use)),
  "button-group": dynamic(() => import("./button-group/use").then((m) => m.Use)),
  "calendar": dynamic(() => import("./calendar/use").then((m) => m.Use)),
  "callout": dynamic(() => import("./callout/use").then((m) => m.Use)),
  "card": dynamic(() => import("./card/use").then((m) => m.Use)),
  "carousel": dynamic(() => import("./carousel/use").then((m) => m.Use)),
  "chart": dynamic(() => import("./chart/use").then((m) => m.Use)),
  "checkbox": dynamic(() => import("./checkbox/use").then((m) => m.Use)),
  "chip": dynamic(() => import("./chip/use").then((m) => m.Use)),
  "collapsible": dynamic(() => import("./collapsible/use").then((m) => m.Use)),
  "combobox": dynamic(() => import("./combobox/use").then((m) => m.Use)),
  "command": dynamic(() => import("./command/use").then((m) => m.Use)),
  "context-menu": dynamic(() => import("./context-menu/use").then((m) => m.Use)),
  "crumb-bar": dynamic(() => import("./crumb-bar/use").then((m) => m.Use)),
  "data-table": dynamic(() => import("./data-table/use").then((m) => m.Use)),
  "date-picker": dynamic(() => import("./date-picker/use").then((m) => m.Use)),
  "dialog": dynamic(() => import("./dialog/use").then((m) => m.Use)),
  "drawer": dynamic(() => import("./drawer/use").then((m) => m.Use)),
  "dropdown-menu": dynamic(() => import("./dropdown-menu/use").then((m) => m.Use)),
  "empty": dynamic(() => import("./empty/use").then((m) => m.Use)),
  "field": dynamic(() => import("./field/use").then((m) => m.Use)),
  "form": dynamic(() => import("./form/use").then((m) => m.Use)),
  "hover-card": dynamic(() => import("./hover-card/use").then((m) => m.Use)),
  "icons": dynamic(() => import("./icons/use").then((m) => m.Use)),
  "inline-form": dynamic(() => import("./inline-form/use").then((m) => m.Use)),
  "input": dynamic(() => import("./input/use").then((m) => m.Use)),
  "input-group": dynamic(() => import("./input-group/use").then((m) => m.Use)),
  "input-otp": dynamic(() => import("./input-otp/use").then((m) => m.Use)),
  "item": dynamic(() => import("./item/use").then((m) => m.Use)),
  "kbd": dynamic(() => import("./kbd/use").then((m) => m.Use)),
  "label": dynamic(() => import("./label/use").then((m) => m.Use)),
  "link": dynamic(() => import("./link/use").then((m) => m.Use)),
  "menubar": dynamic(() => import("./menubar/use").then((m) => m.Use)),
  "native-select": dynamic(() => import("./native-select/use").then((m) => m.Use)),
  "navigation-menu": dynamic(() => import("./navigation-menu/use").then((m) => m.Use)),
  "pagination": dynamic(() => import("./pagination/use").then((m) => m.Use)),
  "popover": dynamic(() => import("./popover/use").then((m) => m.Use)),
  "progress": dynamic(() => import("./progress/use").then((m) => m.Use)),
  "radio": dynamic(() => import("./radio/use").then((m) => m.Use)),
  "references": dynamic(() => import("./references/use").then((m) => m.Use)),
  "resizable": dynamic(() => import("./resizable/use").then((m) => m.Use)),
  "scroll-area": dynamic(() => import("./scroll-area/use").then((m) => m.Use)),
  "select": dynamic(() => import("./select/use").then((m) => m.Use)),
  "separator": dynamic(() => import("./separator/use").then((m) => m.Use)),
  "sheet": dynamic(() => import("./sheet/use").then((m) => m.Use)),
  "sidebar": dynamic(() => import("./sidebar/use").then((m) => m.Use)),
  "skeleton": dynamic(() => import("./skeleton/use").then((m) => m.Use)),
  "slider": dynamic(() => import("./slider/use").then((m) => m.Use)),
  "spinner": dynamic(() => import("./spinner/use").then((m) => m.Use)),
  "stepper": dynamic(() => import("./stepper/use").then((m) => m.Use)),
  "switch": dynamic(() => import("./switch/use").then((m) => m.Use)),
  "table": dynamic(() => import("./table/use").then((m) => m.Use)),
  "tabs": dynamic(() => import("./tabs/use").then((m) => m.Use)),
  "textarea": dynamic(() => import("./textarea/use").then((m) => m.Use)),
  "theme-toggle": dynamic(() => import("./theme-toggle/use").then((m) => m.Use)),
  "toast": dynamic(() => import("./toast/use").then((m) => m.Use)),
  "toggle": dynamic(() => import("./toggle/use").then((m) => m.Use)),
  "toggle-group": dynamic(() => import("./toggle-group/use").then((m) => m.Use)),
  "tooltip": dynamic(() => import("./tooltip/use").then((m) => m.Use)),
  "workflow": dynamic(() => import("./workflow/use").then((m) => m.Use)),
};

export function UseSlot({ name }: { name: string }) {
  const Use = uses[name];
  if (!Use) return null;
  return <Use />;
}
