export const interfaces = [
  {
    slug: "line",
    title: "AI chat",
    voice: "Discuss Deftones lyrics through close reading.",
    law: "A focused music-analysis assistant with supporting interpretation beside the conversation.",
    story:
      "A focused assistant for discussing Deftones lyrics without reproducing them. The conversation list stays compact, the active reading gets the widest column, and deeper interpretation opens beside the thread instead of interrupting it.",
    what: "AI chat",
    type: "Chat list, thread, line inspector",
    module: "Grid system",
    ink: "Neutral surfaces, hairline dividers, and a quiet active state.",
    use: "Choose a song → ask a question → develop a reading",
    field: "Compact rail, centered reading measure, persistent composer.",
    note: "Replies are simulated locally, so the study can be explored without sending text to a model.",
    components: ["Button", "Icon", "Input", "Input group"],
    modifications: [
      "Inputs were joined into one edge-to-edge composer, with equal padding on every side and a fixed send action.",
      "Buttons and icons were reduced to compact, text-first controls for the conversation rail and inspector.",
      "Selected rows use a tonal field and hairline division instead of pills, preserving the flat Vlak structure.",
    ],
  },
  {
    slug: "press",
    title: "Dashboard",
    voice: "Monitor output and open a job sheet.",
    law: "An operations dashboard for scanning output, jobs, and production detail.",
    story:
      "An operations dashboard for a print floor. A shift lead can scan weekly output, compare job status, and open the production sheet without leaving the overview.",
    what: "Dashboard",
    type: "Rail, metrics, job sheet",
    module: "Grid system",
    ink: "Neutral chrome with one red signal reserved for live production.",
    use: "Scan metrics → select a job → open its sheet",
    field: "Three summary metrics above throughput and job detail.",
    note: "Changing the range recalculates the same measures, preserving orientation between week and month views.",
    components: ["Toggle group", "Icon"],
    modifications: [
      "The toggle group was tightened into a range switch with shared borders and flush internal edges.",
      "Icons were aligned to the metric baseline and used only where they improve scanning.",
      "Summary blocks borrow the card structure but remove corner rounding so the dashboard reads as one continuous grid.",
    ],
  },
  {
    slug: "wall",
    title: "Social feed",
    voice: "Share work, comment, and open a profile.",
    law: "A studio feed where work stays primary and discussion remains close by.",
    story:
      "A studio feed built around work in progress. Images lead, short notes provide context, and comments open beside the feed so the visual rhythm stays intact.",
    what: "Social feed",
    type: "Feed, comments, profile",
    module: "Grid system",
    ink: "Photographs carry the field; neutral controls and hairlines stay secondary.",
    use: "Browse work → open comments → view a contributor",
    field: "People in the rail, masonry feed in the center, context on the right.",
    note: "Profiles remain secondary to the work and use the same side pane as comments.",
    components: ["Avatar", "Button", "Card", "Icon"],
    modifications: [
      "Cards were made image-first, with the media area larger than the text area and edges aligned to the feed grid.",
      "Avatars were scaled down for authorship cues and paired with names rather than treated as decorative portraits.",
      "At narrow widths, the rail becomes compact navigation and the masonry feed collapses to a single mobile column.",
    ],
  },
  {
    slug: "night",
    title: "Fleet management",
    voice: "Track vehicles and inspect a trip.",
    law: "A dispatch view that connects fleet status, location, and trip detail.",
    story:
      "A dispatch view for a compact urban fleet. The unit list provides status at a glance, the map establishes location, and the trip pane reveals only the selected vehicle’s details.",
    what: "Fleet management",
    type: "City field, units, trip",
    module: "Grid system",
    ink: "Muted map tones with one red position marker and high-contrast controls.",
    use: "Scan fleet → select a vehicle → inspect its trip",
    field: "Status rail, city-scale map, and an on-demand detail pane.",
    note: "The list keeps one visual scale so an alert changes priority without changing the surrounding layout.",
    components: ["Button", "Icon"],
    modifications: [
      "List rows were expanded into status-rich fleet records while retaining the base item spacing and divider logic.",
      "The right-hand detail pane uses an icon-only close button fixed to its top-right corner.",
      "Map controls and vehicle states use square, flush targets rather than floating rounded controls.",
    ],
  },
  {
    slug: "evening",
    title: "Order out",
    voice: "Filter kitchens, choose a dish, and review the bag.",
    law: "A local ordering flow that keeps discovery, selection, and checkout connected.",
    story:
      "A local ordering flow designed to move from discovery to decision quickly. Filters reduce the field, photography carries the menu, and the bag opens beside the market instead of replacing it.",
    what: "Order out",
    type: "Market, store, bag",
    module: "Grid system",
    ink: "Large food photography, restrained controls, and clear selected states.",
    use: "Filter kitchens → choose a dish → review the bag",
    field: "Search and filters above an image-led market; details open alongside it.",
    note: "Kitchens, dishes, and the bag share one hierarchy, keeping the transition into checkout predictable.",
    components: ["Input", "Input group", "Toggle group", "Icon"],
    modifications: [
      "Toggle groups were flattened into segmented filters with a restrained tonal selected state and inset keyline.",
      "Market cards enlarge photography beyond the copy block and remove ornamental rounding from the surrounding grid.",
      "Search and filter controls reflow into horizontal, touch-sized groups when the specimen narrows.",
    ],
  },
  {
    slug: "room",
    title: "Team chat",
    voice: "Move between channels, messages, and threads.",
    law: "A team workspace that keeps channels, conversation, and thread context visible.",
    story:
      "A team chat for a small studio. Channels and availability stay in the rail, conversation holds the center, and threads open beside the message that started them.",
    what: "Team chat",
    type: "Channels, messages, thread",
    module: "Grid system",
    ink: "Neutral surfaces, compact avatars, and clear unread and active states.",
    use: "Choose a channel → read or reply → open a thread",
    field: "Channels and people in the rail, messages in the center, thread at right.",
    note: "People and threads use the same contextual pane, keeping the message column stable.",
    components: ["Avatar", "Button", "Icon", "Input", "Input group"],
    modifications: [
      "The sidebar item was stripped of leading icons and given more vertical padding for a quieter text hierarchy.",
      "Avatars were tuned for dense message rows, while thread actions remain aligned to the message baseline.",
      "The input group becomes a full-width composer with a fixed action and equal outer padding.",
    ],
  },
  {
    slug: "graphics",
    title: "Wallpaper generator",
    voice: "Generate and export modernist wallpapers.",
    law: "A local composition tool for producing disciplined, high-resolution desktop fields.",
    story: "A wallpaper generator for brand and product teams. Direction, canvas, and variation controls stay close to the prompt, while three original compositions occupy the main field at a useful reviewing scale.",
    what: "Wallpaper generator",
    type: "Prompt, composition controls, 6K export",
    module: "Grid system",
    ink: "Working chrome stays neutral so color belongs to the generated work.",
    use: "Set direction → generate three fields → export a 6K PNG",
    field: "Control rail beside a large, image-led results canvas.",
    note: "Every composition is generated locally from geometry and color, so it works without an account, API key, or external image service.",
    components: ["Button", "Icon", "Input", "Toggle group"],
    modifications: [
      "The input was enlarged into a multiline direction field while keeping Vlak's border, type, and focus behavior.",
      "Toggle groups became flush canvas selectors; buttons use square edges and fixed heights throughout the tool rail.",
      "Generated fields use the card as an artwork frame, with scalable vector previews and a direct 6K PNG export.",
    ],
  },
  {
    slug: "render",
    title: "3D workspace",
    voice: "Model, inspect, and render a vehicle concept.",
    law: "A professional 3D workspace with dense tools around an uninterrupted viewport.",
    story: "A modeling interface for shaping a compact electric concept car. Toolbars frame the viewport, object properties remain visible, and render status sits in the same chrome as modeling controls.",
    what: "3D workspace",
    type: "Viewport, toolbars, object properties",
    module: "Grid system",
    ink: "Dark production chrome, restrained selection orange, neutral model lighting.",
    use: "Choose a tool → edit geometry → inspect material and render state",
    field: "Full toolbar chrome around a dominant visual viewport.",
    note: "The car is fictional and shown mid-process with wireframe geometry and a selected body panel.",
    components: ["Button", "Icon", "Toggle group"],
    modifications: [
      "Icon buttons were normalized to identical square cells and optically centered inside the vertical tool rail.",
      "Toggle groups were compressed for viewport modes, with adjacent controls sharing borders rather than gaps.",
      "The card surface was opened into a live 3D viewport; tool chrome stays flush to its four edges.",
    ],
  },
  {
    slug: "drive",
    title: "EV controls",
    voice: "Control the cabin, media, charging, and connectivity.",
    law: "An in-car system that keeps driving information primary and secondary controls reachable.",
    story: "A fictional electric Evoque concept interface developed from the vehicle study in the Vlak films. The side profile remains primary while range, route, charging, climate, media, and connectivity sit in one measured landscape display.",
    what: "EV controls",
    type: "Vehicle status, media, climate, connectivity",
    module: "Grid system",
    ink: "Deep cabin black, high-contrast type, electric blue status accents.",
    use: "Check range → navigate or play media → adjust cabin controls",
    field: "Vehicle profile above four equal status and control fields.",
    note: "The Evoque silhouette connects the study to the Vlak films; all electric-system data and interface behavior are fictional.",
    components: ["Button", "Icon", "Progress", "Toggle group"],
    modifications: [
      "The card was expanded into four border-sharing vehicle fields beneath an uninterrupted profile view.",
      "Media and temperature controls use identical square hit areas with optically centered Vlak icons.",
      "Progress was narrowed into battery telemetry, with a warm signal reserved for charge and active state.",
    ],
  },
  {
    slug: "orbit",
    title: "Satellite operations",
    voice: "Observe European assets and review orbital passes.",
    law: "A civil earth-observation console joining coverage, pass timing, and image analysis.",
    story: "A fictional European satellite operations system. Operators can select an observation asset, inspect its current pass, compare spectral layers, and queue a new capture over the North Sea.",
    what: "Satellite operations",
    type: "Earth observation, passes, telemetry",
    module: "Grid system",
    ink: "Dark analytical chrome with cyan telemetry and full-color earth imagery.",
    use: "Select an asset → inspect coverage → queue an observation",
    field: "Asset rail, dominant orbital image, telemetry and pass detail.",
    note: "All organizations, satellites, and telemetry are fictional; the map is illustrative rather than real-time.",
    components: ["Button", "Icon", "Progress", "Toggle group"],
    modifications: [
      "The base card became a flush telemetry panel with dense rows, live values, and no independent corner treatment.",
      "Progress components were narrowed into signal and pass indicators suitable for analytical data.",
      "Buttons and toggles were condensed for operations use, including a fixed-height queue action and square map controls.",
    ],
  },
  {
    slug: "frontier",
    title: "Frontier model company",
    voice: "Present a European AI lab with clarity and restraint.",
    law: "A company landing page that leads with capability, access, and research evidence.",
    story: "A landing page for a fictional European frontier-model company. The proposition is concrete, model access is easy to find, and evaluation results support the claim without turning the page into a dashboard.",
    what: "Frontier model company",
    type: "Marketing page, model overview, research proof",
    module: "Grid system",
    ink: "Editorial white space, black type, and one cobalt research signal.",
    use: "Understand the model → inspect evidence → request access",
    field: "Short navigation, direct hero, capability grid, evaluation band.",
    note: "The company, model, benchmark values, and customer references are entirely fictional.",
    components: ["Button", "Card", "Icon", "Link"],
    modifications: [
      "Cards were opened into border-sharing capability columns so the page reads as one editorial field.",
      "The primary button keeps Vlak's square geometry while links use a quiet directional arrow instead of a second container.",
      "The hero grid was extended into a subtle perspective matrix, with the content anchored to its lower-left edge.",
    ],
  },
  {
    slug: "platforms",
    title: "Mobile platforms",
    voice: "Compare one product flow on iOS and Android.",
    law: "A side-by-side platform study that preserves content while respecting native conventions.",
    story: "The same lightweight travel plan rendered as an iPhone interface and an Android interface. Content, hierarchy, and task order match; navigation, status chrome, controls, and spacing follow each platform.",
    what: "Mobile platforms",
    type: "iOS and Android interface comparison",
    module: "Grid system",
    ink: "Shared content palette with platform-specific navigation and control treatment.",
    use: "Compare the same itinerary, actions, and states across platforms",
    field: "Two complete phone frames shown at equal scale.",
    note: "The comparison avoids pixel-for-pixel duplication: parity comes from shared meaning, not identical chrome.",
    components: ["Button", "Icon", "Tabs"],
    modifications: [
      "Shared content cards were redrawn with flush edges, then spaced according to each platform rather than duplicated pixel for pixel.",
      "Tabs become an iOS bottom bar on one device and Android navigation on the other, while keeping the same destinations.",
      "Buttons and icons inherit native placement and touch sizing without introducing branded platform components into Vlak.",
    ],
  },
] as const;

export type InterfaceSlug = (typeof interfaces)[number]["slug"];

export const INTERFACE_SLUGS = interfaces.map((item) => item.slug);

export function interfaceBySlug(slug: string) {
  return interfaces.find((item) => item.slug === slug);
}
