export const interfaces = [
  {
    slug: "line",
    title: "AI chat",
    voice: "Write, revise, and inspect a line.",
    law: "A focused writing assistant with revision tools beside the conversation.",
    story:
      "A focused writing assistant for shaping short passages. The conversation list stays compact, the active draft gets the widest column, and revisions open beside the thread instead of interrupting it.",
    what: "AI chat",
    type: "Chat list, thread, line inspector",
    module: "Grid system",
    ink: "Neutral surfaces, hairline dividers, and a quiet active state.",
    use: "Choose a conversation → write → revise a response",
    field: "Compact rail, centered reading measure, persistent composer.",
    note: "Replies are simulated locally, so the study can be explored without sending text to a model.",
    components: ["Button", "Icon", "Input", "Input group"],
  },
  {
    slug: "press",
    title: "Dashboard",
    voice: "Monitor output and open a job sheet.",
    law: "An operations dashboard for scanning output, jobs, and production detail.",
    story:
      "An operations dashboard for a print floor. A shift lead can scan weekly output, compare job status, and open the production sheet without leaving the overview.",
    what: "Dashboard",
    type: "Rail, metrics, job sheet",
    module: "Grid system",
    ink: "Neutral chrome with one red signal reserved for live production.",
    use: "Scan metrics → select a job → open its sheet",
    field: "Three summary metrics above throughput and job detail.",
    note: "Changing the range recalculates the same measures, preserving orientation between week and month views.",
    components: ["Toggle group", "Icon"],
  },
  {
    slug: "wall",
    title: "Social feed",
    voice: "Share work, comment, and open a profile.",
    law: "A studio feed where work stays primary and discussion remains close by.",
    story:
      "A studio feed built around work in progress. Images lead, short notes provide context, and comments open beside the feed so the visual rhythm stays intact.",
    what: "Social feed",
    type: "Feed, comments, profile",
    module: "Grid system",
    ink: "Photographs carry the field; neutral controls and hairlines stay secondary.",
    use: "Browse work → open comments → view a contributor",
    field: "People in the rail, masonry feed in the center, context on the right.",
    note: "Profiles remain secondary to the work and use the same side pane as comments.",
    components: ["Avatar", "Button", "Card", "Icon"],
  },
  {
    slug: "night",
    title: "Fleet management",
    voice: "Track vehicles and inspect a trip.",
    law: "A dispatch view that connects fleet status, location, and trip detail.",
    story:
      "A dispatch view for a compact urban fleet. The unit list provides status at a glance, the map establishes location, and the trip pane reveals only the selected vehicle’s details.",
    what: "Fleet management",
    type: "City field, units, trip",
    module: "Grid system",
    ink: "Muted map tones with one red position marker and high-contrast controls.",
    use: "Scan fleet → select a vehicle → inspect its trip",
    field: "Status rail, city-scale map, and an on-demand detail pane.",
    note: "The list keeps one visual scale so an alert changes priority without changing the surrounding layout.",
    components: ["Button", "Icon"],
  },
  {
    slug: "evening",
    title: "Order out",
    voice: "Filter kitchens, choose a dish, and review the bag.",
    law: "A local ordering flow that keeps discovery, selection, and checkout connected.",
    story:
      "A local ordering flow designed to move from discovery to decision quickly. Filters reduce the field, photography carries the menu, and the bag opens beside the market instead of replacing it.",
    what: "Order out",
    type: "Market, store, bag",
    module: "Grid system",
    ink: "Large food photography, restrained controls, and clear selected states.",
    use: "Filter kitchens → choose a dish → review the bag",
    field: "Search and filters above an image-led market; details open alongside it.",
    note: "Kitchens, dishes, and the bag share one hierarchy, keeping the transition into checkout predictable.",
    components: ["Input", "Input group", "Toggle group", "Icon"],
  },
  {
    slug: "room",
    title: "Team chat",
    voice: "Move between channels, messages, and threads.",
    law: "A team workspace that keeps channels, conversation, and thread context visible.",
    story:
      "A team chat for a small studio. Channels and availability stay in the rail, conversation holds the center, and threads open beside the message that started them.",
    what: "Team chat",
    type: "Channels, messages, thread",
    module: "Grid system",
    ink: "Neutral surfaces, compact avatars, and clear unread and active states.",
    use: "Choose a channel → read or reply → open a thread",
    field: "Channels and people in the rail, messages in the center, thread at right.",
    note: "People and threads use the same contextual pane, keeping the message column stable.",
    components: ["Avatar", "Button", "Icon", "Input", "Input group"],
  },
  {
    slug: "graphics",
    title: "Graphic generator",
    voice: "Generate and refine modernist brand graphics.",
    law: "A creative tool for producing disciplined brand artwork from a written direction.",
    story: "A graphic generation workspace for brand teams. Direction and format controls stay close to the prompt, while finished poster options occupy the main canvas at a useful reviewing scale.",
    what: "Graphic generator",
    type: "Prompt, art direction, generated outputs",
    module: "Grid system",
    ink: "Working chrome stays neutral so color belongs to the generated work.",
    use: "Set direction → generate options → select an output",
    field: "Control rail beside a large, image-led results canvas.",
    note: "The outputs are original generated artworks, not placeholders or reproductions of historical posters.",
    components: ["Button", "Icon", "Input", "Toggle group"],
  },
  {
    slug: "render",
    title: "3D workspace",
    voice: "Model, inspect, and render a vehicle concept.",
    law: "A professional 3D workspace with dense tools around an uninterrupted viewport.",
    story: "A modeling interface for shaping a compact electric concept car. Toolbars frame the viewport, object properties remain visible, and render status sits in the same chrome as modeling controls.",
    what: "3D workspace",
    type: "Viewport, toolbars, object properties",
    module: "Grid system",
    ink: "Dark production chrome, restrained selection orange, neutral model lighting.",
    use: "Choose a tool → edit geometry → inspect material and render state",
    field: "Full toolbar chrome around a dominant visual viewport.",
    note: "The car is fictional and shown mid-process with wireframe geometry and a selected body panel.",
    components: ["Button", "Icon", "Toggle group"],
  },
  {
    slug: "drive",
    title: "EV controls",
    voice: "Control the cabin, media, charging, and connectivity.",
    law: "An in-car system that keeps driving information primary and secondary controls reachable.",
    story: "A fictional European EV cockpit. Speed, range, route guidance, media, climate, phone, and charging share one calm landscape display without imitating a production vehicle.",
    what: "EV controls",
    type: "Vehicle status, media, climate, connectivity",
    module: "Grid system",
    ink: "Deep cabin black, high-contrast type, electric blue status accents.",
    use: "Check range → navigate or play media → adjust cabin controls",
    field: "Driving status at left, active task at center, quick controls at right.",
    note: "Large targets and short labels keep the secondary interface readable at a glance.",
    components: ["Button", "Icon", "Progress", "Toggle group"],
  },
  {
    slug: "orbit",
    title: "Satellite operations",
    voice: "Observe European assets and review orbital passes.",
    law: "A civil earth-observation console joining coverage, pass timing, and image analysis.",
    story: "A fictional European satellite operations system. Operators can select an observation asset, inspect its current pass, compare spectral layers, and queue a new capture over the North Sea.",
    what: "Satellite operations",
    type: "Earth observation, passes, telemetry",
    module: "Grid system",
    ink: "Dark analytical chrome with cyan telemetry and full-color earth imagery.",
    use: "Select an asset → inspect coverage → queue an observation",
    field: "Asset rail, dominant orbital image, telemetry and pass detail.",
    note: "All organizations, satellites, and telemetry are fictional; the map is illustrative rather than real-time.",
    components: ["Button", "Icon", "Progress", "Toggle group"],
  },
  {
    slug: "frontier",
    title: "Frontier model company",
    voice: "Present a European AI lab with clarity and restraint.",
    law: "A company landing page that leads with capability, access, and research evidence.",
    story: "A landing page for a fictional European frontier-model company. The proposition is concrete, model access is easy to find, and evaluation results support the claim without turning the page into a dashboard.",
    what: "Frontier model company",
    type: "Marketing page, model overview, research proof",
    module: "Grid system",
    ink: "Editorial white space, black type, and one cobalt research signal.",
    use: "Understand the model → inspect evidence → request access",
    field: "Short navigation, direct hero, capability grid, evaluation band.",
    note: "The company, model, benchmark values, and customer references are entirely fictional.",
    components: ["Button", "Card", "Icon", "Link"],
  },
  {
    slug: "platforms",
    title: "Mobile platforms",
    voice: "Compare one product flow on iOS and Android.",
    law: "A side-by-side platform study that preserves content while respecting native conventions.",
    story: "The same lightweight travel plan rendered as an iPhone interface and an Android interface. Content, hierarchy, and task order match; navigation, status chrome, controls, and spacing follow each platform.",
    what: "Mobile platforms",
    type: "iOS and Android interface comparison",
    module: "Grid system",
    ink: "Shared content palette with platform-specific navigation and control treatment.",
    use: "Compare the same itinerary, actions, and states across platforms",
    field: "Two complete phone frames shown at equal scale.",
    note: "The comparison avoids pixel-for-pixel duplication: parity comes from shared meaning, not identical chrome.",
    components: ["Button", "Icon", "Tabs"],
  },
] as const;

export type InterfaceSlug = (typeof interfaces)[number]["slug"];

export const INTERFACE_SLUGS = interfaces.map((item) => item.slug);

export function interfaceBySlug(slug: string) {
  return interfaces.find((item) => item.slug === slug);
}
