/**
 * Raster component registry: the interface kit as data. This is the
 * single source the docs site, the CLI, the generated registry JSON,
 * and the integrity tests all read from. Each entry names the CSS
 * classes involved, the source files that implement it, and carries a
 * minimal markup snippet in the house style.
 */

import type { RasterComponent } from "./schema";

export type { RasterComponent } from "./schema";

export const rasterComponents: RasterComponent[] = [
  {
    name: "button",
    title: "Button",
    description: "Solid ink primary and 1px ghost. 40px tall; 36px small.",
    category: "actions",
    classes: ["rs-btn-primary", "rs-btn-ghost", "rs-btn-sm"],
    css: ["components/button.css"],
    react: "components/button.tsx",
    snippet: `<button class="rs-btn-primary">Primary action</button>\n<button class="rs-btn-ghost">Secondary</button>`,
  },
  {
    name: "button-group",
    title: "Button group",
    description: "Joined ghost buttons with a 1px rule between.",
    category: "actions",
    classes: ["rs-btn-group"],
    css: ["components/button-group.css"],
    react: "components/button-group.tsx",
    registryDependencies: ["button"],
    snippet: `<div class="rs-btn-group"><button class="rs-btn-ghost">Left</button><button class="rs-btn-ghost">Center</button><button class="rs-btn-ghost">Right</button></div>`,
  },
  {
    name: "link",
    title: "Text link",
    description: "Text link with a hairline underline. In-copy variant is inset 1px.",
    category: "actions",
    classes: ["rs-link", "rs-link-underline"],
    css: ["components/link.css"],
    snippet: `<div><a class="rs-link" href="#">A text link</a></div>\n<div><a class="rs-link-underline" href="#">An in-copy link</a></div>`,
  },
  {
    name: "input",
    title: "Input",
    description: "Text field. 1px border, ink focus, 12px label above.",
    category: "forms",
    classes: ["rs-field", "rs-field-label", "rs-input", "rs-input-full", "rs-input-ok", "rs-feedback", "rs-feedback-ok"],
    css: ["components/field.css"],
    react: "components/input.tsx",
    snippet: `<div class="rs-field"><span class="rs-field-label">E-mail</span><input class="rs-input rs-input-full" /></div>`,
  },
  {
    name: "label",
    title: "Label",
    description: "12px secondary label, set above the control.",
    category: "forms",
    classes: ["rs-label"],
    css: ["components/field.css"],
    react: "components/label.tsx",
    snippet: `<label class="rs-label" for="name">Name</label>`,
  },
  {
    name: "field",
    title: "Field",
    description: "Label, control, and a hint or error stacked in one cell.",
    category: "forms",
    classes: ["rs-field", "rs-field-label", "rs-field-hint", "rs-field-error"],
    css: ["components/field.css"],
    react: "components/field.tsx",
    registryDependencies: ["input"],
    snippet: `<div class="rs-field"><label class="rs-field-label">Name</label><input class="rs-input rs-input-full" /><p class="rs-field-hint">As it appears on the invoice.</p></div>`,
  },
  {
    name: "input-group",
    title: "Input group",
    description: "Addon and field share a 1px border.",
    category: "forms",
    classes: ["rs-input-group", "rs-input-addon", "rs-input-group-end"],
    css: ["components/input-group.css"],
    react: "components/input-group.tsx",
    registryDependencies: ["input"],
    snippet: `<div class="rs-input-group"><span class="rs-input-addon">https://</span><input class="rs-input" placeholder="raster.noord.dev" /></div>`,
  },
  {
    name: "native-select",
    title: "Native select",
    description: "Native select with Raster 1px chrome.",
    category: "forms",
    classes: ["rs-native-select"],
    css: ["components/native-select.css"],
    react: "components/native-select.tsx",
    snippet: `<select class="rs-native-select"><option>Alkmaar</option><option>Amsterdam</option><option>Rotterdam</option></select>`,
  },
  {
    name: "inline-form",
    title: "Inline form",
    description: "One field with the submit action inside. The button appears after the input validates.",
    category: "patterns",
    classes: ["rs-inline-field", "rs-inline-input", "rs-inline-btn", "rs-reveal", "rs-reveal-in", "rs-subscribed"],
    css: ["components/inline-form.css"],
    react: "components/inline-form.tsx",
    registryDependencies: ["button"],
    snippet: `<div class="rs-inline-field"><input class="rs-inline-input" placeholder="Your e-mail" /><span class="rs-reveal rs-reveal-in"><button class="rs-btn-primary rs-inline-btn">Subscribe</button></span></div>`,
  },
  {
    name: "radio",
    title: "Radio",
    description: "Single-choice control. Selected dot is ink.",
    category: "forms",
    classes: ["rs-radio", "rs-radio-dot", "rs-radio-on"],
    css: ["components/radio.css"],
    react: "components/radio.tsx",
    snippet: `<label class="rs-radio"><span class="rs-radio-dot rs-radio-on"></span>Monthly</label>`,
  },
  {
    name: "checkbox",
    title: "Checkbox",
    description: "Multi-choice. 16px box, 3px radius, ink fill when checked.",
    category: "forms",
    classes: ["rs-choice", "rs-check", "rs-check-on"],
    css: ["components/checkbox.css"],
    react: "components/checkbox.tsx",
    snippet: `<label class="rs-choice"><span class="rs-check rs-check-on"><svg viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"><path d="M3.5 8.5 L6.5 11.5 L12.5 4.5" vector-effect="non-scaling-stroke"/></svg></span>Brand</label>`,
  },
  {
    name: "switch",
    title: "Switch",
    description: "32×18 control. On fills ink; off is a 1px track. The thumb moves; the box stays 32px.",
    category: "forms",
    classes: ["rs-switch", "rs-switch-on"],
    css: ["components/switch.css"],
    react: "components/switch.tsx",
    snippet: `<span class="rs-switch rs-switch-on"><i></i></span>`,
  },
  {
    name: "slider",
    title: "Slider",
    description: "2px track, ink fill, 14px thumb.",
    category: "forms",
    classes: ["rs-slider", "rs-slider-fill", "rs-slider-thumb"],
    css: ["components/slider.css"],
    react: "components/slider.tsx",
    snippet: `<div class="rs-slider"><span class="rs-slider-fill" style="width:62%"></span><span class="rs-slider-thumb" style="left:62%"></span></div>`,
  },
  {
    name: "progress",
    title: "Progress",
    description: "4px bar. Percentage is set in the label.",
    category: "feedback",
    classes: ["rs-progress", "rs-progress-head"],
    css: ["components/progress.css"],
    react: "components/progress.tsx",
    snippet: `<div class="rs-progress-head"><span>Uploading</span><span>40%</span></div><div class="rs-progress"><span style="width:40%"></span></div>`,
  },
  {
    name: "tabs",
    title: "Tabs",
    description: "Text tabs in one row. Active tab has a 1px underline.",
    category: "navigation",
    classes: ["rs-tabs", "rs-tab", "rs-tab-active"],
    css: ["components/tabs.css"],
    react: "components/tabs.tsx",
    snippet: `<div class="rs-tabs"><span class="rs-tab rs-tab-active">Overview</span><span class="rs-tab">Activity</span><span class="rs-tab">Settings</span></div>`,
  },
  {
    name: "breadcrumbs",
    title: "Breadcrumbs",
    description: "Ancestor links, 40% slashes, current page at full ink.",
    category: "navigation",
    classes: ["rs-crumbs", "rs-crumbs-link", "rs-crumbs-sep", "rs-crumbs-here"],
    css: ["components/breadcrumbs.css"],
    react: "components/breadcrumbs.tsx",
    snippet: `<p class="rs-crumbs"><a class="rs-crumbs-link" href="/">Studio</a><span class="rs-crumbs-sep">/</span><span class="rs-crumbs-here">Raster</span></p>`,
  },
  {
    name: "crumb-bar",
    title: "Crumb bar",
    description: "Fixed 72px bar. Transparent at rest; scrolled state adds paper, a bottom 1px, and the trail.",
    category: "navigation",
    classes: [
      "rs-crumb-bar",
      "rs-crumb-bar-scrolled",
      "rs-crumb-bar-inner",
      "rs-crumb-root",
      "rs-crumb-root-full",
      "rs-crumb-root-short",
    ],
    css: ["components/crumb-bar.css"],
    react: "components/crumb-bar.tsx",
    registryDependencies: ["breadcrumbs"],
    snippet: `<nav class="rs-crumb-bar rs-crumb-bar-scrolled"><div class="rs-crumb-bar-inner"><a class="rs-crumb-root" href="/"><span class="rs-crumb-root-full">Raster</span><span class="rs-crumb-root-short">rs</span></a><p class="rs-crumbs"><span>Docs</span><span class="rs-crumbs-sep">/</span><span class="rs-crumbs-here">Components</span></p></div></nav>`,
  },
  {
    name: "pagination",
    title: "Pagination",
    description: "Square page controls. Current page is solid ink.",
    category: "navigation",
    classes: ["rs-pages", "rs-page", "rs-page-on", "rs-page-gap"],
    css: ["components/pagination.css"],
    react: "components/pagination.tsx",
    snippet: `<div class="rs-pages"><span class="rs-page"><svg viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"><path d="M10.5 3.5 L5.5 8 L10.5 12.5" vector-effect="non-scaling-stroke"/></svg></span><span class="rs-page rs-page-on">1</span><span class="rs-page">2</span><span class="rs-page"><svg viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"><path d="M5.5 3.5 L10.5 8 L5.5 12.5" vector-effect="non-scaling-stroke"/></svg></span></div>`,
  },
  {
    name: "select",
    title: "Select",
    description: "Closed trigger with a chevron. The menu overlays the page.",
    category: "forms",
    classes: ["rs-select", "rs-dropdown", "rs-menu", "rs-menu-item", "rs-menu-item-active"],
    css: ["components/menu.css"],
    react: "components/select.tsx",
    snippet: `<button class="rs-dropdown"><span>Alkmaar</span></button>\n<div class="rs-menu"><button class="rs-menu-item rs-menu-item-active">Alkmaar</button><button class="rs-menu-item">Amsterdam</button></div>`,
  },
  {
    name: "dialog",
    title: "Dialog",
    description: "Modal with a title, body, and two equal actions.",
    category: "surfaces",
    classes: ["rs-dialog", "rs-dialog-title", "rs-dialog-body", "rs-dialog-actions"],
    css: ["components/dialog.css"],
    react: "components/dialog.tsx",
    registryDependencies: ["button"],
    snippet: `<div class="rs-dialog"><span class="rs-dialog-title">Remove this item?</span><p class="rs-dialog-body">This can't be undone.</p><div class="rs-dialog-actions"><button class="rs-btn-ghost rs-btn-sm">Cancel</button><button class="rs-btn-primary rs-btn-sm">Remove</button></div></div>`,
  },
  {
    name: "badge",
    title: "Badge",
    description: "11px badge. Outline, solid, and muted fills.",
    category: "feedback",
    classes: ["rs-badge", "rs-badge-solid", "rs-badge-muted"],
    css: ["components/badge.css"],
    react: "components/badge.tsx",
    snippet: `<span class="rs-badge">Recommended</span><span class="rs-badge-solid">Delivered</span><span class="rs-badge-muted">In progress</span>`,
  },
  {
    name: "chip",
    title: "Mono chip",
    description: "Mono identifier with a 1px mixed border.",
    category: "content",
    classes: ["rs-chip"],
    css: ["components/chip.css"],
    snippet: `<span class="rs-chip">/noord-brand</span>`,
  },
  {
    name: "card",
    title: "Card",
    description: "1px frame, chrome-square. Label, title, and body.",
    category: "surfaces",
    classes: ["rs-card", "rs-card-label", "rs-card-title", "rs-card-body", "rs-card-in"],
    css: ["components/card.css"],
    react: "components/card.tsx",
    snippet: `<div class="rs-card"><span class="rs-card-label">Case study</span><h3 class="rs-card-title">A quieter interface</h3><p class="rs-card-body">Emphasis from weight and spacing, never from a hue.</p></div>`,
  },
  {
    name: "concentric-radius",
    title: "Concentric radius",
    description: "Nested frames. Inner radius is the circular-corner fit, clamped at 0.",
    category: "surfaces",
    classes: ["rs-nest", "rs-nest-in"],
    css: ["components/nest.css"],
    react: "components/concentric-radius.tsx",
    snippet: `<div class="rs-nest" style="--rs-out:28px;--rs-gap:16px;width:184px"><div class="rs-nest-in"></div></div>`,
  },
  {
    name: "stepper",
    title: "Stepper",
    description: "Numbered dots joined by 1px lines. Done fills ink; active is outlined.",
    category: "navigation",
    classes: ["rs-steps", "rs-step", "rs-step-dot", "rs-step-done", "rs-step-active", "rs-step-name", "rs-step-sub", "rs-step-line"],
    css: ["components/stepper.css"],
    react: "components/stepper.tsx",
    snippet: `<div class="rs-steps"><div class="rs-step"><span class="rs-step-dot rs-step-done">1</span><span class="rs-step-line"></span><span class="rs-step-name">Brief</span></div><div class="rs-step"><span class="rs-step-dot rs-step-active">2</span><span class="rs-step-name">Design</span></div></div>`,
  },
  {
    name: "table",
    title: "Table",
    description: "Open grid, 1px row rules, last column right-aligned. Total rows use 2px rules.",
    category: "content",
    classes: ["rs-table", "rs-total-row"],
    css: ["components/table.css"],
    snippet: `<table class="rs-table"><thead><tr><th>Phase</th><th>Weeks</th></tr></thead><tbody><tr><td>Strategy</td><td>2</td></tr><tr><td>Identity</td><td>4</td></tr></tbody></table>`,
  },
  {
    name: "icons",
    title: "Icons",
    description: "16 viewBox marks, 1px currentColor, butt/miter. Shipped in the React package.",
    category: "icons",
    classes: [
      "rs-icons",
      "rs-icon",
      "rs-icon-catalog",
      "rs-icon-group",
      "rs-icon-group-title",
      "rs-icon-grid",
      "rs-icon-cell",
      "rs-icon-pair",
      "rs-icon-label",
    ],
    css: ["components/icons.css"],
    react: "components/icon.tsx",
    snippet: `<div class="rs-icons"><svg class="rs-icon" viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"><path d="M6.5 2.5 H13.5 V9.5" vector-effect="non-scaling-stroke"/><rect x="2.5" y="6.5" width="7" height="7" vector-effect="non-scaling-stroke"/></svg><svg class="rs-icon" viewBox="0 0 16 16" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"><path d="M6.5 2.5 H13.5 V9.5" vector-effect="non-scaling-stroke"/><rect x="2.5" y="6.5" width="7" height="7" vector-effect="non-scaling-stroke"/></svg></div>`,
  },
  {
    name: "accordion",
    title: "Accordion",
    description: "Native details rows on 1px rules. Shared name keeps one item open.",
    category: "content",
    classes: ["rs-acc", "rs-acc-item", "rs-acc-chevron", "rs-acc-body"],
    css: ["components/accordion.css"],
    react: "components/accordion.tsx",
    snippet: `<div class="rs-acc"><details class="rs-acc-item" name="faq" open><summary>What is Raster?<svg class="rs-acc-chevron" viewBox="0 0 16 16" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"><g transform="rotate(90 8 8)"><path d="M5.5 3.5 L10.5 8 L5.5 12.5" vector-effect="non-scaling-stroke"/></g></svg></summary><div class="rs-acc-body">A monochrome, CSS-first design system.</div></details><details class="rs-acc-item" name="faq"><summary>Is it dependency-free?<svg class="rs-acc-chevron" viewBox="0 0 16 16" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"><g transform="rotate(90 8 8)"><path d="M5.5 3.5 L10.5 8 L5.5 12.5" vector-effect="non-scaling-stroke"/></g></svg></summary><div class="rs-acc-body">Yes. Native elements do the work.</div></details></div>`,
  },
  {
    name: "alert",
    title: "Alert",
    description: "1px frame with an icon. Solid ink variant for critical.",
    category: "feedback",
    classes: ["rs-alert", "rs-alert-title", "rs-alert-body", "rs-alert-solid"],
    css: ["components/alert.css"],
    react: "components/alert.tsx",
    snippet: `<div class="rs-alert" role="status"><div><span class="rs-alert-title">Heads up</span><p class="rs-alert-body">Your workspace syncs every hour.</p></div></div>`,
  },
  {
    name: "alert-dialog",
    title: "Alert dialog",
    description: "Native dialog that must be answered. Escape and light dismiss are off.",
    category: "surfaces",
    classes: ["rs-dialog", "rs-dialog-title", "rs-dialog-body", "rs-dialog-actions"],
    css: ["components/dialog.css"],
    react: "components/alert-dialog.tsx",
    registryDependencies: ["dialog", "button"],
    snippet: `<dialog class="rs-dialog" open><span class="rs-dialog-title">Delete this workspace?</span><p class="rs-dialog-body">All projects go with it.</p><div class="rs-dialog-actions"><button class="rs-btn-ghost rs-btn-sm">Cancel</button><button class="rs-btn-primary rs-btn-sm">Delete</button></div></dialog>`,
  },
  {
    name: "avatar",
    title: "Avatar",
    description: "32px circle of initials, or a covering image. Broken images fall back. Rows overlap 8px.",
    category: "content",
    classes: ["rs-avatar", "rs-avatar-sm", "rs-avatar-lg", "rs-avatar-row"],
    css: ["components/avatar.css"],
    react: "components/avatar.tsx",
    snippet: `<div class="rs-avatar-row"><span class="rs-avatar">RV</span><span class="rs-avatar">NO</span><span class="rs-avatar">+3</span></div>`,
  },
  {
    name: "item",
    title: "Item",
    description: "Flush row: title and description on the left, meta on the right.",
    category: "content",
    classes: ["rs-item", "rs-item-title", "rs-item-desc", "rs-item-meta"],
    css: ["components/item.css"],
    react: "components/item.tsx",
    snippet: `<div class="rs-item"><div><p class="rs-item-title">Alkmaar</p><p class="rs-item-desc">The studio city.</p></div><span class="rs-item-meta">NL</span></div>`,
  },
  {
    name: "textarea",
    title: "Textarea",
    description: "Multiline field, vertical resize only.",
    category: "forms",
    classes: ["rs-textarea"],
    css: ["components/textarea.css"],
    react: "components/textarea.tsx",
    registryDependencies: ["input"],
    snippet: `<div class="rs-field"><span class="rs-field-label">Notes</span><textarea class="rs-textarea" placeholder="What should we know?"></textarea></div>`,
  },
  {
    name: "separator",
    title: "Separator",
    description: "1px rule, horizontal or vertical.",
    category: "content",
    classes: ["rs-sep", "rs-sep-v"],
    css: ["components/separator.css"],
    react: "components/separator.tsx",
    snippet: `<hr class="rs-sep" />`,
  },
  {
    name: "skeleton",
    title: "Skeleton",
    description: "Divider-tone pulse. Animation stops when prefers-reduced-motion is on.",
    category: "feedback",
    classes: ["rs-skeleton"],
    css: ["components/skeleton.css"],
    react: "components/skeleton.tsx",
    snippet: `<span class="rs-skeleton" style="width:180px;height:14px"></span>`,
  },
  {
    name: "empty",
    title: "Empty",
    description: "Placeholder cell with a title, a sentence, and an optional action.",
    category: "feedback",
    classes: ["rs-empty", "rs-empty-title", "rs-empty-body", "rs-empty-action"],
    css: ["components/empty.css"],
    react: "components/empty.tsx",
    registryDependencies: ["button"],
    snippet: `<div class="rs-empty"><p class="rs-empty-title">No projects yet</p><p class="rs-empty-body">Start one. The grid is empty on purpose.</p><div class="rs-empty-action"><button class="rs-btn-ghost rs-btn-sm">New project</button></div></div>`,
  },
  {
    name: "spinner",
    title: "Spinner",
    description: "16px 1px ring. Animation stops when prefers-reduced-motion is on.",
    category: "feedback",
    classes: ["rs-spinner"],
    css: ["components/spinner.css"],
    react: "components/spinner.tsx",
    snippet: `<span class="rs-spinner" role="status" aria-label="Loading"><svg viewBox="0 0 16 16" width="16" height="16" fill="none"><circle cx="8" cy="8" r="6.5" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-dasharray="28 13" vector-effect="non-scaling-stroke"/></svg></span>`,
  },
  {
    name: "tooltip",
    title: "Tooltip",
    description: "Label on hover and keyboard focus.",
    category: "feedback",
    classes: ["rs-tip"],
    css: ["components/tooltip.css"],
    react: "components/tooltip.tsx",
    registryDependencies: ["button"],
    snippet: `<span class="rs-tip" data-tip="Copy to clipboard"><button class="rs-btn-ghost rs-btn-sm">Copy</button></span>`,
  },
  {
    name: "toast",
    title: "Toast",
    description: "Bottom-right status, aria-live polite, four-second dismiss.",
    category: "feedback",
    classes: ["rs-toasts", "rs-toast", "rs-toast-title", "rs-toast-body"],
    css: ["components/toast.css"],
    react: "components/toast.tsx",
    snippet: `<div class="rs-toasts" role="status"><div class="rs-toast"><div><span class="rs-toast-title">Saved</span><p class="rs-toast-body">Your changes are live.</p></div></div></div>`,
  },
  {
    name: "dropdown-menu",
    title: "Dropdown menu",
    description: "Action menu with menuitem roles and arrow-key movement.",
    category: "actions",
    classes: ["rs-menu", "rs-menu-item", "rs-menu-sep"],
    css: ["components/menu.css", "components/menu-extras.css"],
    react: "components/dropdown-menu.tsx",
    registryDependencies: ["select", "button"],
    snippet: `<div class="rs-menu" role="menu"><button class="rs-menu-item" role="menuitem">Rename</button><button class="rs-menu-item" role="menuitem">Duplicate</button><hr class="rs-menu-sep" /><button class="rs-menu-item" role="menuitem">Delete</button></div>`,
  },
  {
    name: "toggle",
    title: "Toggle",
    description: "Pressable control. Pressed fills ink. State is aria-pressed.",
    category: "actions",
    classes: ["rs-toggle", "rs-toggle-group"],
    css: ["components/toggle.css"],
    react: "components/toggle.tsx",
    snippet: `<div class="rs-toggle-group"><button class="rs-toggle" aria-pressed="true">Left</button><button class="rs-toggle" aria-pressed="false">Center</button><button class="rs-toggle" aria-pressed="false">Right</button></div>`,
  },
  {
    name: "toggle-group",
    title: "Toggle group",
    description: "Joined toggles, one pressed, 1px between.",
    category: "actions",
    classes: ["rs-toggle-group"],
    css: ["components/toggle.css"],
    react: "components/toggle-group.tsx",
    registryDependencies: ["toggle"],
    snippet: `<div class="rs-toggle-group"><button class="rs-toggle" aria-pressed="true">Left</button><button class="rs-toggle" aria-pressed="false">Center</button><button class="rs-toggle" aria-pressed="false">Right</button></div>`,
  },
  {
    name: "popover",
    title: "Popover",
    description: "Native Popover API. Top layer, light dismiss.",
    category: "surfaces",
    classes: ["rs-popover", "rs-popover-title", "rs-popover-body"],
    css: ["components/popover.css"],
    react: "components/popover.tsx",
    registryDependencies: ["button"],
    snippet: `<button class="rs-btn-ghost rs-btn-sm" popovertarget="info">Details</button>\n<div id="info" popover="auto" class="rs-popover"><span class="rs-popover-title">Module grid</span><p class="rs-popover-body">204px modules: a 184px column and a 20px gutter.</p></div>`,
  },
  {
    name: "sheet",
    title: "Sheet",
    description: "Native dialog docked to a screen edge, with the platform focus trap and backdrop.",
    category: "surfaces",
    classes: ["rs-sheet", "rs-sheet-left", "rs-sheet-title", "rs-sheet-body"],
    css: ["components/sheet.css"],
    react: "components/sheet.tsx",
    snippet: `<dialog class="rs-sheet" open><span class="rs-sheet-title">Filters</span><p class="rs-sheet-body">Everything narrows from here.</p></dialog>`,
  },
  {
    name: "drawer",
    title: "Drawer",
    description: "Native dialog from the bottom edge, with the platform focus trap and backdrop.",
    category: "surfaces",
    classes: ["rs-drawer", "rs-drawer-title", "rs-drawer-body"],
    css: ["components/drawer.css"],
    react: "components/drawer.tsx",
    snippet: `<dialog class="rs-drawer" open><span class="rs-drawer-title">Notes</span><p class="rs-drawer-body">A bottom panel. Escape closes it.</p></dialog>`,
  },
  {
    name: "scroll-area",
    title: "Scroll area",
    description: "Overflow box with the scrollbar hidden and 20px feathers at the ends.",
    category: "content",
    classes: ["rs-scroll"],
    css: ["components/scroll-area.css"],
    react: "components/scroll-area.tsx",
    snippet: `<div class="rs-scroll" style="max-height:140px" tabindex="0"><p>Alkmaar</p><p>Amsterdam</p><p>Delft</p><p>Eindhoven</p><p>Groningen</p><p>Haarlem</p><p>Rotterdam</p><p>Utrecht</p></div>`,
  },
  {
    name: "chart",
    title: "Charts",
    description: "Line on a 204 field. 1px grid, ink marks. Series use solid, dashed, gray, or dotted. One optional spot color.",
    category: "charts",
    classes: ["rs-chart", "rs-chart-line", "rs-chart-grid", "rs-chart-axis", "rs-chart-bar", "rs-spark"],
    css: ["components/chart.css"],
    react: "components/chart.tsx",
    snippet: `<div class="rs-chart"><svg viewBox="0 0 240 64" width="240" height="64"><line class="rs-chart-grid" x1="0" x2="240" y1="56" y2="56"/><path class="rs-chart-line" d="M0 44 L40 36 L80 40 L120 22 L160 26 L200 12 L240 16"/></svg></div>`,
  },
  {
    name: "bar-chart",
    title: "Bar chart",
    description: "Vertical or horizontal. Thin ink bars, square ends. Stacks when series share a field.",
    category: "charts",
    classes: ["rs-chart-bar"],
    css: ["components/chart.css"],
    react: "components/chart.tsx",
    registryDependencies: ["chart"],
    snippet: `<div class="rs-chart"><svg viewBox="0 0 240 64" width="240" height="64"><line class="rs-chart-grid" x1="0" x2="240" y1="56" y2="56"/><rect class="rs-chart-bar" x="20" y="18" width="8" height="38"/><rect class="rs-chart-bar" x="48" y="10" width="8" height="46"/><rect class="rs-chart-bar" x="76" y="24" width="8" height="32"/></svg></div>`,
  },
  {
    name: "area-chart",
    title: "Area chart",
    description: "Filled field under the first series. 1px grid, textured series, one optional spot color.",
    category: "charts",
    classes: ["rs-chart-area"],
    css: ["components/chart.css"],
    react: "components/chart.tsx",
    registryDependencies: ["chart"],
    snippet: `<div class="rs-chart"><svg viewBox="0 0 240 64" width="240" height="64"><path class="rs-chart-area" d="M0 44 L40 36 L80 40 L120 22 L160 26 L200 12 L240 16 L240 56 L0 56 Z"/><path class="rs-chart-line" d="M0 44 L40 36 L80 40 L120 22 L160 26 L200 12 L240 16"/></svg></div>`,
  },
  {
    name: "scatter-chart",
    title: "Scatter chart",
    description: "Marks on a 1px grid. Ink, or one optional spot color.",
    category: "charts",
    classes: ["rs-chart-mark"],
    css: ["components/chart.css"],
    react: "components/chart.tsx",
    registryDependencies: ["chart"],
    snippet: `<div class="rs-chart"><svg viewBox="0 0 240 64" width="240" height="64"><line class="rs-chart-grid" x1="0" x2="240" y1="56" y2="56"/><circle class="rs-chart-mark" cx="36" cy="40" r="2"/><circle class="rs-chart-mark" cx="88" cy="22" r="2"/><circle class="rs-chart-mark" cx="140" cy="30" r="2"/><circle class="rs-chart-mark" cx="196" cy="14" r="2"/></svg></div>`,
  },
  {
    name: "donut",
    title: "Donut or share",
    description: "Ring against its total, or a flush share strip. 1px stroke.",
    category: "charts",
    classes: ["rs-chart-donut"],
    css: ["components/chart.css"],
    react: "components/chart.tsx",
    registryDependencies: ["chart"],
    snippet: `<div class="rs-chart"><svg class="rs-chart-donut" viewBox="0 0 96 96" width="96" height="96"><circle cx="48" cy="48" r="36" fill="none" stroke="currentColor" stroke-width="1"/></svg></div>`,
  },
  {
    name: "histogram",
    title: "Histogram",
    description: "Histogram. Adjacent bins, 1px between.",
    category: "charts",
    classes: ["rs-chart-hist"],
    css: ["components/chart.css"],
    react: "components/chart.tsx",
    registryDependencies: ["chart"],
    snippet: `<div class="rs-chart"><svg viewBox="0 0 240 64" width="240" height="64"><rect class="rs-chart-hist" x="8" y="36" width="36" height="20"/><rect class="rs-chart-hist" x="45" y="20" width="36" height="36"/><rect class="rs-chart-hist" x="82" y="8" width="36" height="48"/><rect class="rs-chart-hist" x="119" y="24" width="36" height="32"/></svg></div>`,
  },
  {
    name: "small-multiples",
    title: "Small multiples",
    description: "Repeated charts on the same axes. One 184 column per panel.",
    category: "charts",
    classes: ["rs-chart-multi"],
    css: ["components/chart.css"],
    react: "components/chart.tsx",
    registryDependencies: ["chart"],
    snippet: `<div class="rs-chart-multi"><div class="rs-chart"><svg viewBox="0 0 184 64" width="184" height="64"><path class="rs-chart-line" d="M0 40 L46 28 L92 34 L138 16 L184 22"/></svg></div><div class="rs-chart"><svg viewBox="0 0 184 64" width="184" height="64"><path class="rs-chart-line" d="M0 30 L46 36 L92 22 L138 28 L184 18"/></svg></div></div>`,
  },
  {
    name: "collapsible",
    title: "Collapsible",
    description: "Native details disclosure.",
    category: "content",
    classes: ["rs-disclosure", "rs-disclosure-body"],
    css: ["components/collapsible.css"],
    react: "components/collapsible.tsx",
    registryDependencies: ["accordion"],
    snippet: `<details class="rs-disclosure"><summary>Show the details<svg class="rs-acc-chevron" viewBox="0 0 16 16" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"><g transform="rotate(90 8 8)"><path d="M5.5 3.5 L10.5 8 L5.5 12.5" vector-effect="non-scaling-stroke"/></g></svg></summary><div class="rs-disclosure-body">Here they are.</div></details>`,
  },
  {
    name: "hover-card",
    title: "Hover card",
    description: "Preview panel on hover and keyboard focus.",
    category: "surfaces",
    classes: ["rs-hover-card", "rs-hover-card-panel"],
    css: ["components/hover-card.css"],
    react: "components/hover-card.tsx",
    snippet: `<span class="rs-hover-card"><span tabindex="0">@noord</span><span class="rs-hover-card-panel">Noord, a venture studio in Alkmaar. Ten portfolio companies, one design system.</span></span>`,
  },
  {
    name: "kbd",
    title: "Kbd",
    description: "Mono key cap with a 1px frame and a heavier bottom edge.",
    category: "content",
    classes: ["rs-kbd", "rs-kbd-pair"],
    css: ["components/kbd.css"],
    react: "components/kbd.tsx",
    snippet: `<kbd class="rs-kbd">⌘</kbd> <kbd class="rs-kbd">K</kbd>`,
  },
  {
    name: "input-otp",
    title: "One-time code",
    description: "One cell per character. Auto-advance, backspace, and paste.",
    category: "forms",
    classes: ["rs-otp"],
    css: ["components/input-otp.css"],
    react: "components/input-otp.tsx",
    snippet: `<div class="rs-otp"><input maxlength="1" value="8" /><input maxlength="1" value="2" /><input maxlength="1" /><input maxlength="1" /></div>`,
  },
  {
    name: "context-menu",
    title: "Context menu",
    description: "Menu at the pointer on right-click. Escape and outside click close it.",
    category: "actions",
    classes: ["rs-menu", "rs-menu-item", "rs-menu-sep"],
    css: ["components/menu.css", "components/menu-extras.css"],
    react: "components/context-menu.tsx",
    registryDependencies: ["select", "dropdown-menu"],
    snippet: `<div class="rs-menu" role="menu"><button class="rs-menu-item" role="menuitem">Copy</button><button class="rs-menu-item" role="menuitem">Paste</button><hr class="rs-menu-sep" /><button class="rs-menu-item" role="menuitem">Inspect</button></div>`,
  },
  {
    name: "menubar",
    title: "Menubar",
    description: "Row of dropdowns in a 1px strip.",
    category: "actions",
    classes: ["rs-menubar"],
    css: ["components/menubar.css"],
    react: "components/menubar.tsx",
    registryDependencies: ["dropdown-menu", "select"],
    snippet: `<div class="rs-menubar" role="menubar"><button class="rs-dropdown"><span>File</span></button><button class="rs-dropdown"><span>Edit</span></button><button class="rs-dropdown"><span>View</span></button></div>`,
  },
  {
    name: "navigation-menu",
    title: "Navigation menu",
    description: "Horizontal links. The current page is full ink.",
    category: "navigation",
    classes: ["rs-nav"],
    css: ["components/nav.css"],
    react: "components/navigation-menu.tsx",
    snippet: `<nav class="rs-nav"><a href="#" aria-current="page">Overview</a><a href="#">Docs</a><a href="#">Changelog</a></nav>`,
  },
  {
    name: "sidebar",
    title: "Sidebar",
    description: "204-wide rail with a head, nav, and foot. 1px on all four sides.",
    category: "navigation",
    classes: ["rs-sidebar", "rs-sidebar-head", "rs-sidebar-nav", "rs-sidebar-item", "rs-sidebar-label", "rs-sidebar-foot"],
    css: ["components/sidebar.css"],
    react: "components/sidebar.tsx",
    snippet: `<aside class="rs-sidebar"><div class="rs-sidebar-head">Raster</div><nav class="rs-sidebar-nav"><p class="rs-sidebar-label">Go to</p><a class="rs-sidebar-item" aria-current="page">Overview</a><a class="rs-sidebar-item" href="#">Docs</a><a class="rs-sidebar-item" href="#">Components</a></nav><div class="rs-sidebar-foot">0.3</div></aside>`,
  },
  {
    name: "carousel",
    title: "Carousel",
    description: "Scroll-snap track. Buttons nudge one slide; ends feather.",
    category: "content",
    classes: ["rs-carousel", "rs-carousel-track", "rs-carousel-slide", "rs-carousel-nav"],
    css: ["components/carousel.css"],
    react: "components/carousel.tsx",
    registryDependencies: ["pagination"],
    snippet: `<div class="rs-carousel"><div class="rs-carousel-track"><div class="rs-carousel-slide">One</div><div class="rs-carousel-slide">Two</div><div class="rs-carousel-slide">Three</div></div><div class="rs-carousel-nav"><button class="rs-page"><svg viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"><path d="M10.5 3.5 L5.5 8 L10.5 12.5" vector-effect="non-scaling-stroke"/></svg></button><button class="rs-page"><svg viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"><path d="M5.5 3.5 L10.5 8 L5.5 12.5" vector-effect="non-scaling-stroke"/></svg></button></div></div>`,
  },
  {
    name: "resizable",
    title: "Resizable",
    description: "Two panes split by a draggable 1px handle. Arrows move it; value is in ARIA.",
    category: "surfaces",
    classes: ["rs-split", "rs-split-pane", "rs-split-handle"],
    css: ["components/resizable.css"],
    react: "components/resizable.tsx",
    snippet: `<div class="rs-split"><div class="rs-split-pane" style="width:50%">Left</div><button class="rs-split-handle" role="separator" aria-valuenow="50"></button><div class="rs-split-pane" style="width:50%">Right</div></div>`,
  },
  {
    name: "combobox",
    title: "Combobox",
    description: "Text field with a filtered listbox.",
    category: "forms",
    classes: ["rs-combobox", "rs-combobox-empty"],
    css: ["components/combobox.css"],
    react: "components/combobox.tsx",
    registryDependencies: ["input", "select"],
    snippet: `<div class="rs-combobox"><input class="rs-input rs-input-full" role="combobox" placeholder="Search…" /><div class="rs-menu" role="listbox"><button class="rs-menu-item rs-menu-item-active" role="option">Alkmaar</button><button class="rs-menu-item" role="option">Amsterdam</button></div></div>`,
  },
  {
    name: "command",
    title: "Command",
    description: "Command palette in a native dialog. Filter, arrows, enter.",
    category: "actions",
    classes: ["rs-command", "rs-command-input", "rs-command-list", "rs-command-group", "rs-command-item", "rs-command-item-active", "rs-command-hint", "rs-command-empty"],
    css: ["components/command.css"],
    react: "components/command.tsx",
    registryDependencies: ["dialog"],
    snippet: `<div class="rs-command" style="border:1px solid var(--divider);border-radius:var(--radius)"><input class="rs-command-input" placeholder="Type a command or search…" /><div class="rs-command-list"><div class="rs-command-group">Go to</div><button class="rs-command-item rs-command-item-active"><span>Components</span><span class="rs-command-hint">⌘1</span></button><button class="rs-command-item"><span>Tokens</span><span class="rs-command-hint">⌘2</span></button></div></div>`,
  },
  {
    name: "calendar",
    title: "Calendar",
    description: "Month grid. Selected day is ink; today is a 1px outline. Weeks start Monday.",
    category: "forms",
    classes: ["rs-cal", "rs-cal-head", "rs-cal-title", "rs-cal-nav", "rs-cal-grid", "rs-cal-dow", "rs-cal-day", "rs-cal-day-out", "rs-cal-day-today", "rs-cal-day-selected"],
    css: ["components/calendar.css"],
    react: "components/calendar.tsx",
    registryDependencies: ["pagination"],
    snippet: `<div class="rs-cal"><div class="rs-cal-head"><span class="rs-cal-title">July 2026</span><span class="rs-cal-nav"><button class="rs-page"><svg viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"><path d="M10.5 3.5 L5.5 8 L10.5 12.5" vector-effect="non-scaling-stroke"/></svg></button><button class="rs-page"><svg viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"><path d="M5.5 3.5 L10.5 8 L5.5 12.5" vector-effect="non-scaling-stroke"/></svg></button></span></div><div class="rs-cal-grid"><span class="rs-cal-dow">Mo</span><span class="rs-cal-dow">Tu</span><span class="rs-cal-dow">We</span><span class="rs-cal-dow">Th</span><span class="rs-cal-dow">Fr</span><span class="rs-cal-dow">Sa</span><span class="rs-cal-dow">Su</span><button class="rs-cal-day">20</button><button class="rs-cal-day">21</button><button class="rs-cal-day">22</button><button class="rs-cal-day">23</button><button class="rs-cal-day rs-cal-day-selected">24</button><button class="rs-cal-day rs-cal-day-today">25</button><button class="rs-cal-day">26</button></div></div>`,
  },
  {
    name: "date-picker",
    title: "Date picker",
    description: "1px trigger that opens a calendar overlay.",
    category: "forms",
    classes: ["rs-dropdown", "rs-cal"],
    css: ["components/menu.css", "components/calendar.css"],
    react: "components/date-picker.tsx",
    registryDependencies: ["select", "calendar"],
    snippet: `<button class="rs-dropdown"><span>24 July 2026</span></button>`,
  },
  {
    name: "data-table",
    title: "Data table",
    description: "Sortable table. Headers expose aria-sort.",
    category: "content",
    classes: ["rs-datatable-sort", "rs-datatable-empty"],
    css: ["components/datatable.css"],
    react: "components/data-table.tsx",
    registryDependencies: ["table"],
    snippet: `<table class="rs-table"><thead><tr><th><button class="rs-datatable-sort">Phase</button></th><th>Weeks</th></tr></thead><tbody><tr><td>Identity</td><td>4</td></tr><tr><td>Strategy</td><td>2</td></tr></tbody></table>`,
  },
  {
    name: "aspect-ratio",
    title: "Aspect ratio",
    description: "Box that holds a ratio. Media fills it.",
    category: "content",
    classes: ["rs-ratio"],
    css: ["components/ratio.css"],
    react: "components/aspect-ratio.tsx",
    snippet: `<div class="rs-ratio" style="aspect-ratio:16/9;max-width:280px;background:var(--divider-subtle)"></div>`,
  },
  {
    name: "form",
    title: "Form",
    description: "Stacked fields with one primary action at the end.",
    category: "forms",
    classes: ["rs-form"],
    css: ["components/field.css"],
    react: "components/form.tsx",
    registryDependencies: ["field", "input", "button"],
    snippet: `<form class="rs-form"><div class="rs-field"><span class="rs-field-label">Name</span><input class="rs-input rs-input-full" /></div><div class="rs-field"><span class="rs-field-label">E-mail</span><input class="rs-input rs-input-full" /></div><button class="rs-btn-primary">Send</button></form>`,
  },
  {
    name: "workflow",
    title: "Workflow card",
    description: "Dashed 1px pipeline step. Drag handle, dashed chips, ghost add-step.",
    category: "patterns",
    classes: ["rs-flow", "rs-flow-step", "rs-flow-num", "rs-flow-subs", "rs-flow-sub-add", "rs-flow-add", "rs-flow-plus"],
    css: ["components/flow.css"],
    snippet: `<div class="rs-flow" style="grid-template-columns:184px;width:184px"><div class="rs-flow-step"><span class="rs-flow-num">1</span><h4>Proposal</h4><p>Scope, timeline, and fee on one page.</p><div class="rs-flow-subs"><span>Brief</span><span>Fee</span><span class="rs-flow-sub-add">+</span></div></div><button type="button" class="rs-flow-add"><span class="rs-flow-plus">+</span> Add a step</button></div>`,
  },
  {
    name: "assistant",
    title: "Assistant panel",
    description: "Chat panel: user block, reply, suggestion card, input row.",
    category: "patterns",
    classes: ["rs-ai", "rs-ai-head", "rs-ai-title", "rs-ai-status", "rs-ai-msg", "rs-ai-user", "rs-ai-user-block", "rs-ai-reply", "rs-ai-card", "rs-ai-tag", "rs-ai-text", "rs-ai-done", "rs-ai-input", "rs-ai-send"],
    css: ["components/assistant.css"],
    snippet: `<div class="rs-ai"><div class="rs-ai-msg rs-ai-user"><div class="rs-ai-user-block">Make the intro tighter.</div></div><p class="rs-ai-reply">Done. Two sentences, same claim.</p></div>`,
  },
  {
    name: "theme-toggle",
    title: "Theme toggle",
    description: "Icon that swaps moon and sun with the color scheme. Saved in localStorage.",
    category: "actions",
    classes: ["rs-theme-toggle", "rs-theme-toggle-inline", "rs-theme-sun", "rs-theme-moon"],
    css: ["components/theme-toggle.css"],
    react: "components/theme-toggle.tsx",
    snippet: `<button class="rs-theme-toggle rs-theme-toggle-inline" aria-label="Toggle color scheme"><svg class="rs-theme-moon" viewBox="0 0 16 16" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"><path d="M10.5 3.5 A5.5 5.5 0 1 0 10.5 12.5 A4 4 0 1 1 10.5 3.5" vector-effect="non-scaling-stroke"/></svg></button>`,
  },
  {
    name: "callout",
    title: "Callout",
    description: "Note in running copy. 1px frame, 3px ink left edge, slight Raster radius.",
    category: "feedback",
    classes: ["rs-callout"],
    css: ["components/callout.css"],
    snippet: `<div class="rs-callout"><p><strong>Fixed fee.</strong> The number on the cover is the number on the invoice.</p></div>`,
  },
  {
    name: "references",
    title: "References",
    description: "Inline citations, a numbered 1px list, and a cite box. Numerals hang in the gutter.",
    category: "content",
    classes: ["rs-cite", "rs-refs", "rs-ref-authors", "rs-ref-doi", "rs-cite-box", "rs-cite-box-label", "rs-cite-box-text"],
    css: ["components/refs.css"],
    snippet: `<p>Set in a single ink.<sup class="rs-cite"><a href="#ref-1">1</a></sup></p><ol class="rs-refs"><li id="ref-1"><span class="rs-ref-authors">Müller-Brockmann, J.</span> Grid systems in graphic design. <a class="rs-ref-doi" href="#">niggli.ch/grid</a></li></ol>`,
  },
];
