/**
 * Raster component registry — the interface kit as data. This is the
 * single source the docs site, the CLI, the generated registry JSON,
 * and the integrity tests all read from. Each entry names the CSS
 * classes involved, the source files that implement it, and carries a
 * minimal markup snippet in the house style.
 */

import type { RasterComponent } from "./schema";

export type { RasterComponent } from "./schema";

export const rasterComponents: RasterComponent[] = [
  {
    name: "button",
    title: "Button",
    description:
      "Solid ink primary — one per view — and a hairline ghost secondary. 40px tall, 36px small variant.",
    category: "actions",
    classes: ["rs-btn-primary", "rs-btn-ghost", "rs-btn-sm"],
    css: ["components/button.css"],
    react: "components/button.tsx",
    snippet: `<button class="rs-btn-primary">Primary action</button>\n<button class="rs-btn-ghost">Secondary</button>`,
  },
  {
    name: "link",
    title: "Text link",
    description: "Underlined by its hairline; never colored.",
    category: "actions",
    classes: ["rs-link"],
    css: ["components/link.css"],
    snippet: `<a class="rs-link" href="#">A text link</a>`,
  },
  {
    name: "input",
    title: "Input",
    description: "Quiet field: hairline border, ink focus, label above at 12px.",
    category: "forms",
    classes: ["rs-field", "rs-field-label", "rs-input", "rs-input-full", "rs-input-ok", "rs-feedback", "rs-feedback-ok"],
    css: ["components/field.css"],
    react: "components/input.tsx",
    snippet: `<div class="rs-field"><span class="rs-field-label">E-mail</span><input class="rs-input rs-input-full" /></div>`,
  },
  {
    name: "inline-form",
    title: "Inline form",
    description:
      "One field, one action — the action lives inside the field and appears once input validates.",
    category: "patterns",
    classes: ["rs-inline-field", "rs-inline-input", "rs-inline-btn", "rs-reveal", "rs-reveal-in", "rs-subscribed"],
    css: ["components/inline-form.css"],
    react: "components/inline-form.tsx",
    registryDependencies: ["button"],
    snippet: `<div class="rs-inline-field"><input class="rs-inline-input" placeholder="Your e-mail" /><span class="rs-reveal rs-reveal-in"><button class="rs-btn-primary rs-inline-btn">Subscribe</button></span></div>`,
  },
  {
    name: "radio",
    title: "Radio",
    description: "One choice; the dot is ink, never a hue.",
    category: "forms",
    classes: ["rs-radio", "rs-radio-dot", "rs-radio-on"],
    css: ["components/radio.css"],
    react: "components/radio.tsx",
    snippet: `<label class="rs-radio"><span class="rs-radio-dot rs-radio-on"></span>Monthly</label>`,
  },
  {
    name: "checkbox",
    title: "Checkbox",
    description: "Many choices; 16px boxes, 3px radius, ink when checked.",
    category: "forms",
    classes: ["rs-choice", "rs-check", "rs-check-on"],
    css: ["components/checkbox.css"],
    react: "components/checkbox.tsx",
    snippet: `<label class="rs-choice"><span class="rs-check rs-check-on"><svg viewBox="0 0 12 12" fill="none"><path d="M2.5 6.5l2.5 2.5 4.5-5.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span>Brand</label>`,
  },
  {
    name: "switch",
    title: "Switch",
    description: "32×18 pill; on is ink, off is hairline. State moves, layout doesn't.",
    category: "forms",
    classes: ["rs-switch", "rs-switch-on"],
    css: ["components/switch.css"],
    react: "components/switch.tsx",
    snippet: `<span class="rs-switch rs-switch-on"><i></i></span>`,
  },
  {
    name: "slider",
    title: "Slider",
    description: "Thin track with ink fill and 14px thumb.",
    category: "forms",
    classes: ["rs-slider", "rs-slider-fill", "rs-slider-thumb"],
    css: ["components/slider.css"],
    react: "components/slider.tsx",
    snippet: `<div class="rs-slider"><span class="rs-slider-fill" style="width:62%"></span><span class="rs-slider-thumb" style="left:62%"></span></div>`,
  },
  {
    name: "progress",
    title: "Progress",
    description: "4px bar; the percentage lives in the label, never inside the bar.",
    category: "feedback",
    classes: ["rs-progress", "rs-progress-head"],
    css: ["components/progress.css"],
    react: "components/progress.tsx",
    snippet: `<div class="rs-progress-head"><span>Uploading</span><span>40%</span></div><div class="rs-progress"><span style="width:40%"></span></div>`,
  },
  {
    name: "tabs",
    title: "Tabs",
    description: "Active tab is ink with a 1.5px underline.",
    category: "navigation",
    classes: ["rs-tabs", "rs-tab", "rs-tab-active"],
    css: ["components/tabs.css"],
    react: "components/tabs.tsx",
    snippet: `<div class="rs-tabs"><span class="rs-tab rs-tab-active">Overview</span><span class="rs-tab">Activity</span></div>`,
  },
  {
    name: "breadcrumbs",
    title: "Breadcrumbs",
    description: "Slashes at 40% opacity; the current page is ink.",
    category: "navigation",
    classes: ["rs-crumbs", "rs-crumbs-sep", "rs-crumbs-here"],
    css: ["components/breadcrumbs.css"],
    react: "components/breadcrumbs.tsx",
    snippet: `<p class="rs-crumbs"><span>Studio</span><span class="rs-crumbs-sep">/</span><span class="rs-crumbs-here">Raster</span></p>`,
  },
  {
    name: "crumb-bar",
    title: "Crumb bar",
    description:
      "Fixed top bar of the house chrome; transparent at rest, it gains the paper background and its bottom hairline on scroll while the breadcrumbs fade in.",
    category: "navigation",
    classes: ["rs-crumb-bar", "rs-crumb-bar-scrolled", "rs-crumb-bar-inner"],
    css: ["components/crumb-bar.css"],
    react: "components/crumb-bar.tsx",
    registryDependencies: ["breadcrumbs"],
    snippet: `<nav class="rs-crumb-bar rs-crumb-bar-scrolled"><div class="rs-crumb-bar-inner"><p class="rs-crumbs"><span>Raster</span><span class="rs-crumbs-sep">/</span><span class="rs-crumbs-here">Components</span></p></div></nav>`,
  },
  {
    name: "pagination",
    title: "Pagination",
    description: "Squares, not pills; the current page is solid ink.",
    category: "navigation",
    classes: ["rs-pages", "rs-page", "rs-page-on", "rs-page-gap"],
    css: ["components/pagination.css"],
    react: "components/pagination.tsx",
    snippet: `<div class="rs-pages"><span class="rs-page">‹</span><span class="rs-page rs-page-on">1</span><span class="rs-page">2</span><span class="rs-page">›</span></div>`,
  },
  {
    name: "select",
    title: "Select",
    description: "Closed trigger with chevron; the open menu overlays instead of pushing layout.",
    category: "forms",
    classes: ["rs-select", "rs-dropdown", "rs-menu", "rs-menu-item", "rs-menu-item-active"],
    css: ["components/menu.css"],
    react: "components/select.tsx",
    snippet: `<button class="rs-dropdown"><span>Alkmaar</span></button>\n<div class="rs-menu"><button class="rs-menu-item rs-menu-item-active">Alkmaar</button><button class="rs-menu-item">Amsterdam</button></div>`,
  },
  {
    name: "dialog",
    title: "Dialog",
    description: "One question, two equal-sized actions, no third option.",
    category: "surfaces",
    classes: ["rs-dialog", "rs-dialog-title", "rs-dialog-body", "rs-dialog-actions"],
    css: ["components/dialog.css"],
    react: "components/dialog.tsx",
    registryDependencies: ["button"],
    snippet: `<div class="rs-dialog"><span class="rs-dialog-title">Remove this item?</span><p class="rs-dialog-body">This can't be undone.</p><div class="rs-dialog-actions"><button class="rs-btn-ghost rs-btn-sm">Cancel</button><button class="rs-btn-primary rs-btn-sm">Remove</button></div></div>`,
  },
  {
    name: "badge",
    title: "Badge",
    description: "Outline for recommendations, solid for done, muted for pending.",
    category: "feedback",
    classes: ["rs-badge", "rs-badge-solid", "rs-badge-muted"],
    css: ["components/badge.css"],
    react: "components/badge.tsx",
    snippet: `<span class="rs-badge">Recommended</span><span class="rs-badge-solid">Delivered</span><span class="rs-badge-muted">In progress</span>`,
  },
  {
    name: "chip",
    title: "Mono chip",
    description: "Technical identifiers set in the mono stack with a mixed hairline.",
    category: "content",
    classes: ["rs-chip"],
    css: ["components/chip.css"],
    snippet: `<span class="rs-chip">/noord-brand</span>`,
  },
  {
    name: "card",
    title: "Card",
    description: "A hairline frame on the open grid; label, title, body — no heavy chrome.",
    category: "surfaces",
    classes: ["rs-card", "rs-card-label", "rs-card-title", "rs-card-body"],
    css: ["components/card.css"],
    react: "components/card.tsx",
    snippet: `<div class="rs-card"><span class="rs-card-label">Case study</span><h3 class="rs-card-title">A quieter interface</h3><p class="rs-card-body">Emphasis from weight and spacing, never from a hue.</p></div>`,
  },
  {
    name: "stepper",
    title: "Stepper",
    description: "Numbered dots joined by hairlines; done is ink, active is outlined.",
    category: "navigation",
    classes: ["rs-steps", "rs-step", "rs-step-dot", "rs-step-done", "rs-step-active", "rs-step-name", "rs-step-sub", "rs-step-line"],
    css: ["components/stepper.css"],
    react: "components/stepper.tsx",
    snippet: `<div class="rs-steps"><div class="rs-step"><span class="rs-step-dot rs-step-done">1</span><span class="rs-step-name">Brief</span></div><span class="rs-step-line"></span><div class="rs-step"><span class="rs-step-dot rs-step-active">2</span><span class="rs-step-name">Design</span></div></div>`,
  },
  {
    name: "table",
    title: "Table",
    description: "Hairline rows on the open grid; no cell borders, last column right-aligned.",
    category: "content",
    classes: ["rs-table"],
    css: ["components/table.css"],
    snippet: `<table class="rs-table"><thead><tr><th>Phase</th><th>Weeks</th></tr></thead><tbody><tr><td>Strategy</td><td>2</td></tr><tr><td>Identity</td><td>4</td></tr></tbody></table>`,
  },
  {
    name: "icons",
    title: "Icons",
    description: "16/20/24/32px, single-weight 1.5px strokes in currentColor, non-scaling.",
    category: "content",
    classes: ["rs-icons"],
    css: ["components/icons.css"],
    snippet: `<div class="rs-icons"><svg viewBox="0 0 16 16" width="16" height="16" fill="none"><path d="M2.5 8h11M9.5 4l4 4-4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" vector-effect="non-scaling-stroke"/></svg></div>`,
  },
  {
    name: "accordion",
    title: "Accordion",
    description: "Native <details> rows on hairlines; the name attribute keeps one open at a time — no JavaScript at all.",
    category: "content",
    classes: ["rs-acc", "rs-acc-item", "rs-acc-chevron", "rs-acc-body"],
    css: ["components/accordion.css"],
    react: "components/accordion.tsx",
    snippet: `<div class="rs-acc"><details class="rs-acc-item" name="faq" open><summary>What is Raster?<svg class="rs-acc-chevron" viewBox="0 0 16 16" width="16" height="16" fill="none"><path d="M4 6l4 4 4-4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></summary><div class="rs-acc-body">A monochrome, CSS-first design system.</div></details><details class="rs-acc-item" name="faq"><summary>Is it dependency-free?<svg class="rs-acc-chevron" viewBox="0 0 16 16" width="16" height="16" fill="none"><path d="M4 6l4 4 4-4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></summary><div class="rs-acc-body">Yes — native elements do the work.</div></details></div>`,
  },
  {
    name: "alert",
    title: "Alert",
    description: "A hairline frame with an ink icon; solid ink for critical. Emphasis from weight, never a hue.",
    category: "feedback",
    classes: ["rs-alert", "rs-alert-title", "rs-alert-body", "rs-alert-solid"],
    css: ["components/alert.css"],
    react: "components/alert.tsx",
    snippet: `<div class="rs-alert" role="status"><div><span class="rs-alert-title">Heads up</span><p class="rs-alert-body">Your workspace syncs every hour.</p></div></div>`,
  },
  {
    name: "alert-dialog",
    title: "Alert dialog",
    description: "A native <dialog> that requires an explicit answer — Escape and light dismiss are disabled.",
    category: "surfaces",
    classes: ["rs-dialog", "rs-dialog-title", "rs-dialog-body", "rs-dialog-actions"],
    css: ["components/dialog.css"],
    react: "components/alert-dialog.tsx",
    registryDependencies: ["dialog", "button"],
    snippet: `<dialog class="rs-dialog" open><span class="rs-dialog-title">Delete this workspace?</span><p class="rs-dialog-body">All projects go with it.</p><div class="rs-dialog-actions"><button class="rs-btn-ghost rs-btn-sm">Cancel</button><button class="rs-btn-primary rs-btn-sm">Delete</button></div></dialog>`,
  },
  {
    name: "avatar",
    title: "Avatar",
    description: "Initials in a quiet circle; images cover, broken images fall back to initials. Rows overlap on hairlines.",
    category: "content",
    classes: ["rs-avatar", "rs-avatar-sm", "rs-avatar-lg", "rs-avatar-row"],
    css: ["components/avatar.css"],
    react: "components/avatar.tsx",
    snippet: `<div class="rs-avatar-row"><span class="rs-avatar">RV</span><span class="rs-avatar">NO</span><span class="rs-avatar">+3</span></div>`,
  },
  {
    name: "textarea",
    title: "Textarea",
    description: "The quiet field, taller: hairline border, ink focus, vertical resize only.",
    category: "forms",
    classes: ["rs-textarea"],
    css: ["components/textarea.css"],
    react: "components/textarea.tsx",
    registryDependencies: ["input"],
    snippet: `<div class="rs-field"><span class="rs-field-label">Notes</span><textarea class="rs-textarea" placeholder="What should we know?"></textarea></div>`,
  },
  {
    name: "separator",
    title: "Separator",
    description: "A hairline, horizontal or vertical — the only divider the system needs.",
    category: "content",
    classes: ["rs-sep", "rs-sep-v"],
    css: ["components/separator.css"],
    snippet: `<hr class="rs-sep" />`,
  },
  {
    name: "skeleton",
    title: "Skeleton",
    description: "A quiet pulse on the divider tone; perfectly still under prefers-reduced-motion.",
    category: "feedback",
    classes: ["rs-skeleton"],
    css: ["components/skeleton.css"],
    react: "components/skeleton.tsx",
    snippet: `<span class="rs-skeleton" style="width:180px;height:14px"></span>`,
  },
  {
    name: "tooltip",
    title: "Tooltip",
    description: "CSS-only: shows on hover and on keyboard focus alike, ink on paper, no positioning library.",
    category: "feedback",
    classes: ["rs-tip"],
    css: ["components/tooltip.css"],
    react: "components/tooltip.tsx",
    registryDependencies: ["button"],
    snippet: `<span class="rs-tip" data-tip="Copy to clipboard"><button class="rs-btn-ghost rs-btn-sm">Copy</button></span>`,
  },
  {
    name: "toast",
    title: "Toast",
    description: "Quiet confirmations bottom right, announced politely to screen readers, gone in four seconds.",
    category: "feedback",
    classes: ["rs-toasts", "rs-toast", "rs-toast-title", "rs-toast-body"],
    css: ["components/toast.css"],
    react: "components/toast.tsx",
    snippet: `<div class="rs-toasts" role="status"><div class="rs-toast"><div><span class="rs-toast-title">Saved</span><p class="rs-toast-body">Your changes are live.</p></div></div></div>`,
  },
  {
    name: "dropdown-menu",
    title: "Dropdown menu",
    description: "An action menu on the shared overlay surface: keyboard navigation, menu semantics, no layout shift.",
    category: "actions",
    classes: ["rs-menu", "rs-menu-item", "rs-menu-sep"],
    css: ["components/menu.css", "components/menu-extras.css"],
    react: "components/dropdown-menu.tsx",
    registryDependencies: ["select", "button"],
    snippet: `<div class="rs-menu" role="menu"><button class="rs-menu-item" role="menuitem">Rename</button><button class="rs-menu-item" role="menuitem">Duplicate</button><hr class="rs-menu-sep" /><button class="rs-menu-item" role="menuitem">Delete</button></div>`,
  },
  {
    name: "toggle",
    title: "Toggle",
    description: "A press switch and its group; pressed is ink, like everything on. State lives in aria-pressed.",
    category: "actions",
    classes: ["rs-toggle", "rs-toggle-group"],
    css: ["components/toggle.css"],
    react: "components/toggle.tsx",
    snippet: `<div class="rs-toggle-group"><button class="rs-toggle" aria-pressed="true">Left</button><button class="rs-toggle" aria-pressed="false">Center</button><button class="rs-toggle" aria-pressed="false">Right</button></div>`,
  },
  {
    name: "popover",
    title: "Popover",
    description: "The native Popover API: rendered in the top layer, light dismiss for free, anchored by four lines of code.",
    category: "surfaces",
    classes: ["rs-popover", "rs-popover-title", "rs-popover-body"],
    css: ["components/popover.css"],
    react: "components/popover.tsx",
    registryDependencies: ["button"],
    snippet: `<button class="rs-btn-ghost rs-btn-sm" popovertarget="info">Details</button>\n<div id="info" popover="auto" class="rs-popover"><span class="rs-popover-title">Module grid</span><p class="rs-popover-body">204px modules: a 184px column and a 20px gutter.</p></div>`,
  },
  {
    name: "sheet",
    title: "Sheet",
    description: "A native <dialog> parked at the screen edge — platform focus trap and backdrop, hairline seam.",
    category: "surfaces",
    classes: ["rs-sheet", "rs-sheet-left", "rs-sheet-title", "rs-sheet-body"],
    css: ["components/sheet.css"],
    react: "components/sheet.tsx",
    snippet: `<dialog class="rs-sheet" open><span class="rs-sheet-title">Filters</span><p class="rs-sheet-body">Everything narrows from here.</p></dialog>`,
  },
  {
    name: "scroll-area",
    title: "Scroll area",
    description: "Quiet overflow: hidden scrollbar, feathered top and bottom edges — the same treatment the docs TOC uses.",
    category: "content",
    classes: ["rs-scroll"],
    css: ["components/scroll-area.css"],
    react: "components/scroll-area.tsx",
    snippet: `<div class="rs-scroll" style="max-height:140px" tabindex="0"><p>Alkmaar</p><p>Amsterdam</p><p>Delft</p><p>Eindhoven</p><p>Groningen</p><p>Haarlem</p><p>Rotterdam</p><p>Utrecht</p></div>`,
  },
  {
    name: "workflow",
    title: "Workflow card",
    description: "Editable pipeline card: dashed frame, drag handle, dashed chips, ghost add-step card.",
    category: "patterns",
    classes: ["rs-flow", "rs-flow-step", "rs-flow-num", "rs-flow-subs", "rs-flow-sub-add", "rs-flow-add", "rs-flow-plus"],
    css: ["components/flow.css"],
    snippet: `<div class="rs-flow"><div class="rs-flow-step"><span class="rs-flow-num">1</span><h4>Proposal</h4><p>Scope, timeline, and fee on one page.</p></div></div>`,
  },
  {
    name: "assistant",
    title: "Assistant panel",
    description: "Chat surface: user block, replies, suggestion card with applied state, quiet input row.",
    category: "patterns",
    classes: ["rs-ai", "rs-ai-head", "rs-ai-title", "rs-ai-status", "rs-ai-msg", "rs-ai-user", "rs-ai-user-block", "rs-ai-reply", "rs-ai-card", "rs-ai-tag", "rs-ai-text", "rs-ai-done", "rs-ai-input", "rs-ai-send"],
    css: ["components/assistant.css"],
    snippet: `<div class="rs-ai"><div class="rs-ai-msg rs-ai-user"><div class="rs-ai-user-block">Make the intro tighter.</div></div><p class="rs-ai-reply">Done — two sentences, same claim.</p></div>`,
  },
];
